const cars =[
    {
        id: 0,
        image: 'Tesla1.jpg',
        brand: 'Tesla',
        model: 'Model 3 Standard Range Plus',
        title: 'Tesla Model 3 Standard Range Plus',
        price:  57148,
        oldPrice: null,
        location: 'Florida, USA',
        year: 2020,
        fuel: 'Electric',
        drive: 'Rear-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 11,
        ribbonStatus: 'Featured',
        isNew: true

    },
    {
        id: 1,
        image: 'Ford1.jpg',
        brand: 'Ford',
        model: 'F-250 Super Duty',
        title: 'Ford F-250 Super Duty' ,
        price: 82089,
        oldPrice: null,
        location: 'Milan, Italy',
        year: 2021,
        fuel: 'Diesel',
        drive: 'Four-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: 'Featured',
        isNew: true

    },
    {
        id: 2,
        image: 'Honda1.jpg',
        brand: 'Honda',
        model: 'Pilot Touring 7-Passenger',
        title: 'Honda Pilot Touring 7-Passenger',
        price: 43735,
        oldPrice: null,
        location: 'Caracas, Venezuela',
        year: 2021,
        fuel: 'Gasoline',
        drive: 'All-wheel Drive',
        countPassanger: 7,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: true

    },
    {
        id: 3,
        image: 'Chevrolet1.jpg',
        brand: 'Chevrolet',
        model: 'Equinox LS',
        title: 'Chevrolet Equinox LS',
        price: 17978,
        oldPrice: null,
        location: 'Madrid, Spain',
        year: 2017,
        fuel: 'Gasoline',
        drive: 'Front-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: true
    
    },
    {
        id: 4,
        image: 'Kia1.jpg',
        brand: 'Kia',
        model: 'Sorento S',
        title: 'Kia Sorento S',
        price: 29791,
        oldPrice: null,
        location: 'Bangkok, Thailand',
        year: 2021,
        fuel: 'Gasoline',
        drive: 'Front-wheel Drive',
        countPassanger: 7,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: true
    
    },
    {
        id: 5,
        image: 'Mini1.jpg',
        brand: 'MINI',
        model: 'Clubman Cooper S',
        title: 'MINI Clubman Cooper S',
        price: 35850,
        oldPrice: null,
        location: 'Jakarta, Indonesia',
        year: 2022,
        fuel: 'Gasoline',
        drive: 'Front-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: true
    
    },
    {
        id: 6,
        image: 'Jeep1.jpg',
        brand: 'Jeep',
        model: 'Wrangler Unlimited Islander',
        title: 'Jeep Wrangler Unlimited Islander',
        price: 50370,
        oldPrice: null,
        location: 'San Antonio, USA',
        year: 2021,
        fuel: 'Hybrid',
        drive: 'Four-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: false
    
    },
    {
        id: 7,
        image: 'Audi1.jpg',
        brand: 'Audi',
        model: 'e-tron Premium',
        title: 'Audi e-tron Premium',
        price: 72655,
        oldPrice: null,
        location: 'Suwon, South Korea',
        year: 2021,
        fuel: 'Electric',
        drive: 'All-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: false
    
    },
    {
        id: 8,
        image: 'LandRover1.jpg',
        brand: 'Land Rover',
        model: 'Velar R-Dynamic S',
        title: 'Land Rover Velar R-Dynamic S',
        price: 75790,
        oldPrice: null,
        location: 'Jeddah, Saudi Arabia',
        year: 2021,
        fuel: 'Gasoline',
        drive: 'All-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: false
    
    },
    {
        id: 9,
        image: 'Toyota1.jpg',
        brand: 'Toyota',
        model: 'Mirai',
        title: 'Toyota Mirai',
        price: 71415,
        oldPrice: null,
        location: 'Kobe, Japan',
        year: 2021,
        fuel: 'Electric',
        drive: 'Rear-wheel Drive',
        countPassanger: 5,
        rating: 0,
        vievs: 0,
        ribbonStatus: '',
        isNew: false    
    }
];

export default cars